####################
# PHP 8.1 postgres #
####################

php8.1-postgres11:
  variables:
    PHP_VERSION: "8.1"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/postgres:11-alpine"
  extends:
    - .test-template-parallel-scheduled

php8.1-postgres12:
  variables:
    PHP_VERSION: "8.1"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/postgres:12-alpine"
  extends:
    - .test-template-parallel-scheduled

# Supported on:
# - RHEL8
php8.1-postgres13:
  variables:
    PHP_VERSION: "8.1"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/postgres:13-alpine"
  extends:
    - .test-template-parallel

# Supported on:
# - Ubuntu Jammy (22.04)
php8.1-postgres14:
  variables:
    PHP_VERSION: "8.1"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/postgres:14-alpine"
  extends:
    - .test-template-parallel

###################
# PHP 8.1 MariaDB #
###################

php8.1-mariadb10.3:
  variables:
    PHP_VERSION: "8.1"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/mariadb:10.3"
  extends:
    - .test-template-parallel-scheduled

# Supported on:
# - RHEL8
php8.1-mariadb10.5:
  variables:
    PHP_VERSION: "8.1"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/mariadb:10.5"
  extends:
    - .test-template-parallel

# Supported on:
# - Ubuntu Jammy (22.04)
php8.1-mariadb10.6:
  variables:
    PHP_VERSION: "8.1"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/mariadb:10.6"
  extends:
    - .test-template-parallel

#################
# PHP 8.1 MySQL #
#################

php8.1-mysql5.7:
  variables:
    PHP_VERSION: "8.1"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/mysql:5.7"
  extends:
    - .test-template-parallel-scheduled

# Supported on:
# - Ubuntu Jammy (22.04)
# - RHEL8
php8.1-mysql8:
  variables:
    PHP_VERSION: "8.1"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/mysql:8.0"
  extends:
    - .test-template-parallel
