####################
# PHP 8.2 postgres #
####################

php8.2-postgres11:
  variables:
    PHP_VERSION: "8.2"
    DATABASE_ENGINE_VERSION: "$CI_REGISTRY/postgres-11-alpine"
  extends:
    - .test-template-scheduled

php8.2-postgres12:
  variables:
    PHP_VERSION: "8.2"
    DATABASE_ENGINE_VERSION: "$CI_REGISTRY/postgres-12-alpine"
  extends:
    - .test-template-scheduled

php8.2-postgres13:
  variables:
    PHP_VERSION: "8.2"
    DATABASE_ENGINE_VERSION: "$CI_REGISTRY/postgres-13-alpine"
  extends:
    - .test-template-scheduled

php8.2-postgres14:
  variables:
    PHP_VERSION: "8.2"
    DATABASE_ENGINE_VERSION: "$CI_REGISTRY/postgres-14-alpine"
  extends:
    - .test-template-scheduled

###################
# PHP 8.2 MariaDB #
###################

php8.2-mariadb10.3:
  variables:
    PHP_VERSION: "8.2"
    DATABASE_ENGINE_VERSION: "$CI_REGISTRY/mariadb-10.3"
  extends:
    - .test-template-scheduled

php8.2-mariadb10.5:
  variables:
    PHP_VERSION: "8.2"
    DATABASE_ENGINE_VERSION: "$CI_REGISTRY/mariadb-10.5"
  extends:
    - .test-template-scheduled

# Initial support
php8.2-mariadb10.6:
  variables:
    PHP_VERSION: "8.2"
    DATABASE_ENGINE_VERSION: "$CI_REGISTRY/mariadb-10.6"
  extends:
    - .test-template

#################
# PHP 8.2 MySQL #
#################

php8.2-mysql5.7:
  variables:
    PHP_VERSION: "8.2"
    DATABASE_ENGINE_VERSION: "$CI_REGISTRY/mysql-5.7"
  extends:
    - .test-template-scheduled

# Initial support
php8.2-mysql8:
  variables:
    PHP_VERSION: "8.2"
    DATABASE_ENGINE_VERSION: "$CI_REGISTRY/mysql-8.0"
  extends:
    - .test-template
