####################
# PHP 7.4 postgres #
####################

php7.4-postgres11:
  variables:
    PHP_VERSION: "7.4"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/postgres:11-alpine"
  extends:
    - .test-template-parallel-scheduled

# Supported on:
# - Ubuntu focal (20.04)
php7.4-postgres12:
  variables:
    PHP_VERSION: "7.4"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/postgres:12-alpine"
  extends:
    - .test-template-parallel

# Supported on:
# - Debian bullseye
php7.4-postgres13:
  variables:
    PHP_VERSION: "7.4"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/postgres:13-alpine"
  extends:
    - .test-template-parallel-scheduled

php7.4-postgres14:
  variables:
    PHP_VERSION: "7.4"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/postgres:14-alpine"
  extends:
    - .test-template-parallel-scheduled

###################
# PHP 7.4 MariaDB #
###################

php7.4-mariadb10.3:
  variables:
    PHP_VERSION: "7.4"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/mariadb:10.3"
  extends:
    - .test-template-parallel-scheduled

# Supported on:
# - Debian bullseye
php7.4-mariadb10.5:
  variables:
    PHP_VERSION: "7.4"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/mariadb:10.5"
  extends:
    - .test-template-parallel

php7.4-mariadb10.6:
  variables:
    PHP_VERSION: "7.4"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/mariadb:10.6"
  extends:
    - .test-template-parallel-scheduled

#################
# PHP 7.4 MySQL #
#################

# Supported on:
# - Debian bullseye
php7.4-mysql5.7:
  variables:
    PHP_VERSION: "7.4"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/mysql:5.7"
  extends:
    - .test-template-parallel

# Supported on:
# - Debian bullseye
php7.4-mysql8:
  variables:
    PHP_VERSION: "7.4"
    DATABASE_ENGINE_VERSION: "${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/mysql:8.0"
  extends:
    - .test-template-parallel
