default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - stale_schedule

image: alpine:latest

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - unit-test
  - unit-test-parallel
  - package-deps
  - package-build
  - package-tests
  - publish
  - publish-artifacts

include:
  - template: Code-Quality.gitlab-ci.yml
  - local: '/.gitlab-ci/jobs/php_unit_tests/runner.yml'
  - local: '/.gitlab-ci/jobs/php_unit_tests/sequential/php_unit_tests.yml'
  - local: '/.gitlab-ci/jobs/artifact_build.yml'
  - local: '/.gitlab-ci/jobs/debian_package_build.yml'
  - local: '/.gitlab-ci/jobs/packages_tests.yml'
  - local: '/.gitlab-ci/jobs/style_check.yml'
  - local: '/.gitlab-ci/jobs/rpm_package_build.yml'
  - local: '/.gitlab-ci/jobs/repo_backup_operations.yml'

code_quality:
  stage: unit-test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
