language: php

addons:
  apt:
    packages:
    - libgpgme11-dev
    - php5-memcached
    - php5-common
    - php5-curl
    - php5-mcrypt
    - gnupg2

php:
  - 5.5
  - 5.6

env:
  - DB=mysql

services:
  - memcached

matrix:
  fast_finish: true

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction
  - if [ $DB = 'mysql' ]; then sudo apt-get -y install mysql-server; fi
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE passbolt;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE passbolt_test;'; fi"
  - chmod -R 777 ./app/tmp
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]] ; then pecl install timezonedb ; fi
  - echo yes | pecl install gnupg
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
      public \$default = array(
        'datasource' => 'Database/Mysql',
        'database' => 'passbolt',
        'host' => '127.0.0.1',
        'login' => 'travis',
        'password' => '',
        'persistent' => false,
      );
      public \$test = array(
        'datasource' => 'Database/Mysql',
        'database' => 'passbolt_test',
        'host' => '127.0.0.1',
        'login' => 'travis',
        'password' => '',
        'persistent' => false,
      );
    }" > app/Config/database.php
  - cp app/Config/core.php.default app/Config/core.php
  - cp app/Config/app.php.default app/Config/app.php
  - cp app/Config/email.php.default app/Config/email.php
  - sed -i "s/('debug',\s0)/('debug', 2)/" ./app/Config/core.php
  - sed -i "s/DYhG93b0qyJfIxfs2guVoUubWwvniR2G0FgaC9mi/DYhG93b0qyJfIxfs2guVoUubWwvniR2G0FgbC9mi/" ./app/Config/core.php
  - sed -i "s/76859309657453542496749683645/76859309357453542496749683645/" ./app/Config/core.php
  - sed -i "s/\/\/Configure::write('App.fullBaseUrl',\s'http:\/\/example.com');/Configure::write('App.fullBaseUrl', 'http:\/\/127.0.0.1');/" ./app/Config/core.php
  - sed -i "s/\/\/date_default_timezone_set('UTC');/date_default_timezone_set('UTC');/" ./app/Config/core.php
  - sed -i "s/\/home\/www-data\/.gnupg/\/home\/travis\/.gnupg/" ./app/Config/app.php
  - sed -i "s/'App.force_ssl'\s=>\strue/'App.force_ssl' => false/" ./app/Config/app.php
  - sed -i "s/'active'\s=>\sfalse,/'active' => true,/" ./app/Config/app.php

script:
  - mkdir -p build/logs
  - app/Console/cake test app All --stderr --coverage-clover build/logs/clover.xml --configuration=app/Test/phpunit.xml

after_script:
  - php Vendor/bin/coveralls -v

notifications:
  email: false