language: php

addons:
  apt:
    packages: &common_pkg
      - libgpgme11-dev
      - gnupg2

services:
  - memcached

matrix:
  include:
    # PHP 5.4 / MYSQL 5.6
    - php: 5.4
      env: DB=mysql MYSQL_VERSION=5.6
      dist: trusty
      sudo: required
      addons: &php5_addon
        apt:
          packages:
            - *common_pkg
            - php5-memcached
            - php5-common
            - php5-curl
            - php5-mcrypt
            - php5-mysql

    # PHP 5.5 / MYSQL 5.5
    - php: 5.5
      env: DB=mysql MYSQL_VERSION=5.5
      dist: trusty
      sudo: required
      addons: *php5_addon
      # Mysql 5.5 requires extra operations to be installed.
      before_install: &before_install_mysql55
        - sudo service mysql stop
        - sudo rm -fr /var/lib/mysql
        - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5
        - sudo service mysql restart

    # PHP 5.5 / MYSQL 5.6
    - php: 5.5
      env: DB=mysql MYSQL_VERSION=5.6
      dist: trusty
      sudo: required
      addons: *php5_addon

    # PHP 5.6 / MYSQL 5.5
    - php: 5.6
      env: DB=mysql MYSQL_VERSION=5.5
      dist: trusty
      sudo: required
      addons: *php5_addon
      before_install: *before_install_mysql55

    # PHP 5.6 / MYSQL 5.6
    - php: 5.6
      env: DB=mysql MYSQL_VERSION=5.6
      dist: trusty
      sudo: required
      addons: *php5_addon

    # PHP 5.6 / MYSQL 5.7
    - php: 5.6
      env: DB=mysql MYSQL_VERSION=5.7
      dist: trusty
      sudo: required
      addons: *php5_addon
      # Mysql 5.7 requires extra operations to be installed.
      before_install: &before_install_mysql57
        - echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
        - wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
        - sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
        - sudo apt-get update -q
        - sudo apt-get install -q -y --force-yes -o Dpkg::Options::=--force-confnew mysql-server
        - sudo mysql_upgrade
        - sudo service mysql restart

    # PHP 7.0 / MYSQL 5.6
    - php: 7.0
      env: DB=mysql MYSQL_VERSION=5.6
      dist: trusty
      sudo: required
      addons: &php7_addon
        apt:
          packages:
            - *common_pkg

  allow_failures:
    - php: 5.6
      env: DB=mysql MYSQL_VERSION=5.7
    - php: 7.0
      env: DB=mysql MYSQL_VERSION=5.6

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE passbolt;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE passbolt_test;'; fi"
  - chmod -R 777 ./app/tmp
  - sh -c "if [ '$PHPCS' = '1' ]; then composer global require 'cakephp/cakephp-codesniffer:1.*'; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then ~/.composer/vendor/bin/phpcs --config-set installed_paths ~/.composer/vendor/cakephp/cakephp-codesniffer; fi"
  - echo yes | pecl install gnupg
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [[ $TRAVIS_PHP_VERSION = 5.5 ]] ; then echo yes | pecl install apcu-4.0.10; fi
  - if [[ $TRAVIS_PHP_VERSION = 5.6 ]] ; then echo yes | pecl install apcu-4.0.10; fi
  - if [[ $TRAVIS_PHP_VERSION = 7.0 ]] ; then echo yes | pecl install channel://pecl.php.net/apcu-5.1.5; fi
  - echo -e "extension = apcu.so\napc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
      public \$default = array(
        'datasource' => 'Database/Mysql',
        'database' => 'passbolt',
        'host' => '127.0.0.1',
        'login' => 'root',
        'password' => '',
        'persistent' => false,
        'prefix' => '',
      );
      public \$test = array(
        'datasource' => 'Database/Mysql',
        'database' => 'passbolt_test',
        'host' => '127.0.0.1',
        'login' => 'root',
        'password' => '',
        'persistent' => false,
        'prefix' => '',
      );
    }" > app/Config/database.php
  - cp app/Config/core.php.default app/Config/core.php
  - cp app/Config/email.php.default app/Config/email.php
  - sed -i "s/('debug',\s0)/('debug', 2)/" ./app/Config/core.php
  - sed -i "s/DYhG93b0qyJfIxfs2guVoUubWwvniR2G0FgaC9mi/DYhG93b0qyJfIxfs2guVoUubWwvniR2G0FgbC9mi/" ./app/Config/core.php
  - sed -i "s/76859309657453542496749683645/76859309357453542496749683645/" ./app/Config/core.php
  - sed -i "s/\/\/Configure::write('App.fullBaseUrl',\s'http:\/\/example.com');/Configure::write('App.fullBaseUrl', 'http:\/\/127.0.0.1');/" ./app/Config/core.php
  - sed -i "s/\/\/date_default_timezone_set('UTC');/date_default_timezone_set('UTC');/" ./app/Config/core.php
  - if [[ $TRAVIS_PHP_VERSION = 7.0 ]] ; then sed -i "s/'defaults' => 'cache'/'defaults' => 'php'/" ./app/Config/core.php ; fi
  - echo "<?php
    \$config = array(
      'App' => array(
        'ssl' => array(
          'force' => false,
        ),
        'registration' => array(
          'public' => true,
        ),
        'selenium' => array(
          'active' => true,
        ),
      ),
      'GPG' => array(
        'env' => array(
          'setenv' => true,
          'home'   => '/home/travis/.gnupg',
        ),
      ),
    );" > app/Config/app.php

script:
  - mkdir -p build/logs
  - if [[ $TRAVIS_PHP_VERSION = 5.6 ]] ; then app/Console/cake test app All --stderr --coverage-clover build/logs/clover.xml --configuration=app/Test/phpunit.xml ; fi
  - if [[ $TRAVIS_PHP_VERSION != 5.6 ]] ; then app/Console/cake test app All --stderr --configuration=app/Test/phpunit.xml ; fi

after_success:
  - if [[ $TRAVIS_PHP_VERSION = 5.6 ]] ; then php Vendor/bin/coveralls -v ; fi

notifications:
  email: false
