.build-template:
  stage: test
  variables:
    BRANCH: release
  script:
    - |
      apk add --update curl && rm -rf /var/cache/apk/*
      curl --request POST \
        --form "token=$CI_JOB_TOKEN" \
        --form "ref=$BRANCH" \
        --form "variables[PASSBOLT_FLAVOUR]=$PASSBOLT_FLAVOUR" \
        --form "variables[UPSTREAM_COMMIT_SHA]=$CI_COMMIT_SHA" \
        --form "variables[UPSTREAM_PROJECT_ID]=$CI_PROJECT_ID" \
        "https://gitlab.com/api/v4/projects/$TRIGGER_PROJECT_ID/trigger/pipeline"
  only:
    refs:
      - release
    variables:
      - $PASSBOLT_FLAVOUR == "pro"

pro-trigger-build:
  variables:
    TRIGGER_PROJECT_ID: $DOWNSTREAM_PROJECT_ID
  extends: .build-template

pro-vm-trigger-build:
  variables:
    TRIGGER_PROJECT_ID: $DOWNSTREAM_VM_PROJECT_ID
  extends: .build-template

ce-trigger-build:
  variables:
    TRIGGER_PROJECT_ID: $DOWNSTREAM_PROJECT_ID
  extends: .build-template
  only:
    variables:
      - $PASSBOLT_FLAVOUR == "ce"

ce-do-trigger-build:
  extends: .build-template
  variables:
    TRIGGER_PROJECT_ID: $DOWNSTREAM_DO_PROJECT_ID
  only:
    variables:
      - $PASSBOLT_FLAVOUR == "ce"
