.build-template:
  stage: publish-artifacts
  needs:
    - debian-stable
    - ubuntu-stable
  variables:
    BRANCH: master
  script:
    - |
      apk add --update curl jq && rm -rf /var/cache/apk/*
      export PASSBOLT_VERSION=$(jq '.version' package.json)
      curl --request POST \
        --form "token=$CI_JOB_TOKEN" \
        --form "ref=$BRANCH" \
        --form "variables[PASSBOLT_FLAVOUR]=$PASSBOLT_FLAVOUR" \
        --form "variables[UPSTREAM_COMMIT_SHA]=$CI_COMMIT_SHA" \
        --form "variables[UPSTREAM_PROJECT_ID]=$CI_PROJECT_ID" \
        --form "variables[PASSBOLT_FLAVOUR]=$PASSBOLT_FLAVOUR" \
        --form "variables[PASSBOLT_VERSION]=$PASSBOLT_VERSION" \
        "https://gitlab.com/api/v4/projects/$TRIGGER_PROJECT_ID/trigger/pipeline"
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /publish-package/'
      when: on_success


docker-trigger-build:
  variables:
    TRIGGER_PROJECT_ID: $DOWNSTREAM_PROJECT_ID
  extends: .build-template

vm-trigger-build:
  variables:
    TRIGGER_PROJECT_ID: $DOWNSTREAM_VM_PROJECT_ID
  extends: .build-template

