services:
  - registry.gitlab.com/passbolt/passbolt-ci-docker-images/dind:latest

.rules:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(snyk-fix*|feature\/debian\_*|master|release)/ || ($CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE == "schedule")'
      when: on_success

.dependencies:
  extends: .rules
  image: $PACKAGE_MANAGER_IMAGE
  stage: package-deps
  artifacts:
    paths:
      - $PACKAGE_MANAGER_PATH
    expire_in: 1 days
    when: on_success
  cache:
    paths:
      - $PACKAGE_MANAGER_PATH

composer:
  extends: .dependencies
  variables:
    PACKAGE_MANAGER_IMAGE: "registry.gitlab.com/passbolt/passbolt-ci-docker-images/composer:latest"
    PACKAGE_MANAGER_PATH: vendor/
  script:
    - |
      composer install --prefer-dist -o --no-dev --ignore-platform-reqs --no-interaction

build-debian:
  extends: .rules
  image: registry.gitlab.com/passbolt/passbolt-ci-docker-images/debian-bullseye-11-slim:latest
  stage: package-build
  variables:
    PASSBOLT_COMPONENT: stable
  dependencies:
    - composer
  artifacts:
    paths:
      - '*.deb'
      - '*.build'
      - '*.buildinfo'
      - '*.changes'
    expire_in: 1 week
    when: on_success
  script:
    - |
      apt-get update
      apt-get install -y git-buildpackage devscripts apt-utils debconf-utils fakeroot equivs cdbs
      if [[ ! -z $NIGHTLY || $CI_COMMIT_BRANCH =~ ^(develop|feature\/debian\_*) ]]; then
        export PASSBOLT_COMPONENT=testing
        gbp dch --snapshot --snapshot-number=$(date +%s) --ignore-branch
      fi
      make -f debian/rules debian/control
      mk-build-deps -irt'apt-get --no-install-recommends -yV' debian/control
      dpkg-checkbuilddeps
      debuild --preserve-envvar PASSBOLT_FLAVOUR --preserve-envvar PASSBOLT_COMPONENT -us -uc -b -i -I
      cp ../*.deb .
      cp ../*.build .
      cp ../*.buildinfo .
      cp ../*.changes .

.publish-apt:
  image: registry.gitlab.com/passbolt/passbolt-ops/passbolt-aptly
  stage: publish
  dependencies:
    - build-debian
  script:
    - /publisher.sh
  retry:
    max: 0

.publish-debian:
  extends: .publish-apt
  variables:
    DISTRIBUTION: buster
    PREFIX: $PASSBOLT_FLAVOUR/debian
  needs:
    - job: "debian-buster-runtime"
    - job: "debian-buster-break"
    - job: "debian-buster-purge"
    - job: "debian-buster-fs"
    - job: "debian-bullseye-runtime"
    - job: "debian-bullseye-break"
    - job: "debian-bullseye-purge"
    - job: "debian-bullseye-fs"
    - job: "build-debian"

publish-debian-testing:
  extends: .publish-debian
  variables:
    PASSBOLT_COMPONENT: testing
    NIGHTLY: "true"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success

publish-debian-stable:
  extends: .publish-debian
  variables:
    PASSBOLT_COMPONENT: stable
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /publish-package/ && $CI_COMMIT_BRANCH == "release"'
      when: on_success

.publish-ubuntu:
  extends: .publish-apt
  variables:
    DISTRIBUTION: focal
  needs:
    - job: "ubuntu-2004-runtime"
    - job: "ubuntu-2004-break"
    - job: "ubuntu-2004-purge"
    - job: "ubuntu-2004-fs"
    - job: "ubuntu-2204-runtime"
    - job: "ubuntu-2204-break"
    - job: "ubuntu-2204-purge"
    - job: "ubuntu-2204-fs"
    - job: "build-debian"

publish-ubuntu-testing:
  extends: .publish-ubuntu
  variables:
    PASSBOLT_COMPONENT: testing
    NIGHTLY: "true"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success

publish-ubuntu-stable:
  extends: .publish-ubuntu
  variables:
    PASSBOLT_COMPONENT: stable
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /publish-package/ && $CI_COMMIT_BRANCH == "release"'
      when: on_success
