help_site_notes:
  stage: release
  variables:
    GPG_KEY_PATH: "/tmp/gpg-key"
    GPG_PASSPHRASE: $HELP_SITE_GPG_KEY_PASS
    GPG_KEY_GRIP: $HELP_SITE_GPG_KEYGRIP
  image: debian
  script: |
    source .gitlab-ci/scripts/bin/set-env.sh "$CI_COMMIT_TAG"
    if is_release_candidate "$tag"; then
      echo "The tag is for a release candidate. Skipping release notes creation..."
      exit 0
    fi
    apt update && apt install -y git curl gpg
    curl -L https://gitlab.com/gitlab-org/cli/-/releases/v1.30.0/downloads/glab_1.30.0_Linux_x86_64.deb  --output glab.deb
    dpkg -i glab.deb
    cat "$HELP_SITE_GPG_KEY" > "$GPG_KEY_PATH"
    bash .gitlab-ci/scripts/bin/help_site.sh
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
      when: on_success
