.gpg-functions: &gpg-functions |
  kms_decrypt() {
    payload="$1"
    echo "$payload" | base64 -d | \
    google-cloud-sdk/bin/gcloud kms decrypt \
      --project "$CRYPTOKEYS_PROJECT" \
      --location "europe-west1" \
      --keyring "$CRYPTOKEYS_KEYRING" \
      --key "$KMS_KEY_NAME" \
      --plaintext-file - \
      --ciphertext-file -
  }

.install-jq-rhel-8: &install-jq-rhel-8
  yum install -y jq ${DEPENDENCIES}

.install-jq-rhel-7: &install-jq-rhel-7
  - yum install -y epel-release
  - yum install -y jq ${DEPENDENCIES}

.build-passbolt-rpm-package: &build-passbolt-rpm-package |
  rpmdev-setuptree
  PKG_VERSION=$(cat rpm/CHANGELOG.md | awk 'match($0, /\[([0-9]+\.[0-9]+\.[0-9]+)\]?/) {print substr($0, RSTART, RLENGTH);exit}' | tr -d "[]")
  PASSBOLT_PKG_VERSION=$(cat rpm/CHANGELOG.md | awk 'match($0, /\[([0-9]+\.[0-9]+\.[0-9]+\-[0-9])\]?/) {print substr($0, RSTART, RLENGTH);exit}' | awk -F "-" '{print $2}' | tr -d "[]")
  /bin/sh rpm/scripts/build-passbolt-server.sh
  cp ~/rpmbuild/RPMS/noarch/passbolt-* .

.build-rpm:
  extends: .rules
  image: registry.gitlab.com/passbolt/passbolt-ci-docker-images/rockylinux-8:latest
  stage: package-build
  dependencies:
    - composer
  artifacts:
    paths:
      - '*.rpm'
    expire_in: 1 week
    when: on_success

.build-zypper:
  extends: .rules
  image: registry.gitlab.com/passbolt/passbolt-ci-docker-images/opensuse-leap-15:latest
  stage: package-build
  dependencies:
    - composer
  artifacts:
    paths:
      - '*.rpm'
    expire_in: 1 week
    when: on_success

build-yum:
  extends: .build-rpm
  variables:
    DEPENDENCIES: "rpmdevtools rpmlint rsync selinux-policy-devel rpm-build bc createrepo_c firewalld"
  script:
    - PKG_VERSION=0.3 /bin/sh rpm/scripts/build-passbolt-selinux.sh
    - *install-jq-rhel-8
    - *build-passbolt-rpm-package

build-yum-7:
  extends: .build-rpm
  image: centos:7
  variables:
    DEPENDENCIES: "rpmdevtools rpmlint rsync selinux-policy-devel rpm-build bc createrepo_c firewalld"
  script:
    - PKG_VERSION=0.3 /bin/sh rpm/scripts/build-passbolt-selinux.sh
    - *install-jq-rhel-7
    - *build-passbolt-rpm-package

build-suse:
  extends: .build-zypper
  variables:
    DEPENDENCIES: "rpmdevtools rpmlint rsync selinux-policy-devel rpm-build bc createrepo_c firewalld"
  script:
    - zypper install -y rpmdevtools rpmlint rsync rpm-build bc jq
    - *build-passbolt-rpm-package



# gcloud sdk https://cloud.google.com/sdk/docs/downloads-versioned-archives
.clone-repo-bucket: &clone-repo-bucket |
  yum install python39 wget -y
  wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/$GCLOUD_PACKAGE_VERSION
  echo "$GCLOUD_SHA256SUM $GCLOUD_PACKAGE_VERSION" | sha256sum -c -
  tar xvf $GCLOUD_PACKAGE_VERSION
  ./google-cloud-sdk/install.sh --quiet
  google-cloud-sdk/bin/gcloud auth activate-service-account --key-file "$PACKAGE_SVC_ACC"
  google-cloud-sdk/bin/gsutil -m cp -r "gs://$REPO" .

.gpg-setup: &gpg-setup
  - *gpg-functions
  - yum install gpg -y && mkdir ~/.gnupg
  - echo "allow-preset-passphrase" >> ~/.gnupg/gpg-agent.conf
  - gpg-connect-agent reloadagent /bye
  - gpg --batch --import <(kms_decrypt "$GPG_KEY" | base64 -d)
  - /usr/libexec/gpg-preset-passphrase --passphrase "$(kms_decrypt $GPG_PASS | base64 -d)" --preset $GPG_KEYGRIP
  - echo "%_signature gpg" > ~/.rpmmacros
  - echo "%_gpg_name $GPG_KEY_ID" >> ~/.rpmmacros

.publish-script: &publish-script |
  yum install -y createrepo_c rpm-sign
  mkdir -p $COMPONENT/$PACKAGE_ARCH
  [ $COMPONENT == "testing" ] && rm -f $COMPONENT/$PACKAGE_ARCH/*rpm
  cp passbolt-*.rpm $COMPONENT/$PACKAGE_ARCH
  rpm --resign $COMPONENT/$PACKAGE_ARCH/*rpm
  createrepo_c --update $COMPONENT
  echo "$(kms_decrypt $GPG_PASS | base64 -d)" | gpg --batch --yes --passphrase-fd 0 --detach-sign --armor testing/repodata/repomd.xml
  google-cloud-sdk/bin/gsutil -m rsync -r -d $COMPONENT "gs://$REPO"
  google-cloud-sdk/bin/gsutil -m setmeta -r -h "Content-Type:text/html" \
    -h "Cache-Control:no-cache" \
    "gs://$REPO"

.publish-rpm:
  image: registry.gitlab.com/passbolt/passbolt-ci-docker-images/rockylinux-8.5
  stage: publish
  variables:
    GCLOUD_SHA256SUM: "81d0ad64dca3e97d02e873d386bafcc77b416d7c9b45e5ec2387e5075b133fc0"
    GCLOUD_PACKAGE_VERSION: "google-cloud-sdk-365.0.0-linux-x86_64.tar.gz"
    COMPONENT: "testing"
    BUCKET_NAME: "download.passbolt.com"
    EL_VERSION: "el8"
    REPO_PATH: "$PASSBOLT_FLAVOUR/rpm/$EL_VERSION"
    REPO: "$BUCKET_NAME/$REPO_PATH/$COMPONENT"
    PACKAGE_ARCH: "noarch"
  before_script:
    - *clone-repo-bucket
    - *gpg-setup
  script:
    - *publish-script
  retry:
    max: 0

.publish-yum-el8:
  extends: .publish-rpm
  needs:
    - job: "almalinux-8-runtime"
    - job: "almalinux-8-break"
    - job: "almalinux-8-purge"
    - job: "almalinux-8-fs"
    - job: "fedora-34-runtime"
    - job: "fedora-34-break"
    - job: "fedora-34-purge"
    - job: "fedora-34-fs"
    - job: "fedora-35-runtime"
    - job: "fedora-35-break"
    - job: "fedora-35-purge"
    - job: "fedora-35-fs"
    - job: "oraclelinux-8-runtime"
    - job: "oraclelinux-8-break"
    - job: "oraclelinux-8-purge"
    - job: "oraclelinux-8-fs"
    - job: "rockylinux-8-runtime"
    - job: "rockylinux-8-break"
    - job: "rockylinux-8-purge"
    - job: "rockylinux-8-fs"
    - job: "rockylinux-9-runtime"
    - job: "rockylinux-9-break"
    - job: "rockylinux-9-purge"
    - job: "rockylinux-9-fs"
    - job: "redhat-9-runtime"
    - job: "redhat-9-break"
    - job: "redhat-9-purge"
    - job: "redhat-9-fs"
    - job: build-yum
      artifacts: true

publish-yum-el8-testing:
  extends: .publish-yum-el8
  variables:
    COMPONENT: "testing"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success

publish-yum-el8-stable:
  extends: .publish-yum-el8
  variables:
    COMPONENT: "stable"
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /publish-package/ && $CI_COMMIT_BRANCH == "release"'
      when: on_success

.publish-yum-el7:
  extends: .publish-rpm
  variables:
    EL_VERSION: "el7"
  needs:
    - job: "centos-7-runtime"
    - job: "centos-7-break"
    - job: "centos-7-purge"
    - job: "centos-7-fs"
    - job: build-yum-7
      artifacts: true

publish-yum-el7-testing:
  extends: .publish-yum-el7
  variables:
    COMPONENT: "testing"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success

publish-yum-el7-stable:
  extends: .publish-yum-el7
  variables:
    COMPONENT: "stable"
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /publish-package/ && $CI_COMMIT_BRANCH == "release"'
      when: on_success


.publish-suse:
  extends: .publish-rpm
  variables:
    EL_VERSION: "opensuse"
  needs:
    - job: "opensuse-leap-15-runtime"
    - job: "opensuse-leap-15-break"
    - job: "opensuse-leap-15-purge"
    - job: "opensuse-leap-15-fs"
    - job: build-suse
      artifacts: true

publish-suse-testing:
  extends: .publish-suse
  variables:
    COMPONENT: "testing"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success

publish-suse-stable:
  extends: .publish-suse
  variables:
    COMPONENT: "stable"
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /publish-package/ && $CI_COMMIT_BRANCH == "release"'
      when: on_success
